-- 코드를 입력하세요
# 자동차 종류가 '세단' 또는 'SUV' 인 자동차
SELECT
    CC.CAR_ID,
    CC.CAR_TYPE,
    TRUNCATE((CC.DAILY_FEE * 30) * (1 - CD.DISCOUNT_RATE / 100), 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CC
NATURAL JOIN (
    SELECT
    CAR_TYPE,
    DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE LIKE '30%') CD
WHERE CAR_TYPE IN ('세단', 'SUV')
AND CAR_ID NOT IN (
    SELECT DISTINCT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%Y-%m-%d') <= '2022-11-30'
    AND DATE_FORMAT(END_DATE, '%Y-%m-%d') >= '2022-11-01')
AND TRUNCATE((CC.DAILY_FEE * 30) * (1 - CD.DISCOUNT_RATE / 100), 0) BETWEEN 500000 AND 2000000
ORDER BY 3 DESC, 2, 1 DESC

# 2022년 11월 1일부터 2022년 11월 30일까지 대여 불가능
# SELECT
#     DISTINCT CAR_ID
#     # ,COUNT(*)
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE
# DATE_FORMAT(START_DATE, '%Y-%m-%d') <= '2022-11-30' AND DATE_FORMAT(END_DATE, '%Y-%m-%d') >= '2022-11-01'
# ORDER BY CAR_ID

# SELECT
#     *
#     # CAR_ID
#     # ,COUNT(*)
# FROM CAR_RENTAL_COMPANY_CAR CC
# LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CR
# ON CC.CAR_ID = CR.CAR_ID
# WHERE CAR_TYPE IN ('세단', 'SUV')

