-- 코드를 입력하세요
SELECT
    YEAR(O.SALES_DATE) AS YEAR,
    MONTH(O.SALES_DATE) AS MONTH,
    COUNT(DISTINCT O.USER_ID) AS PUCHASED_USERS,
    ROUND(COUNT(DISTINCT O.USER_ID) / (SELECT COUNT(USER_ID) FROM USER_INFO WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'),1)
FROM (
    SELECT
        USER_ID,
        JOINED
    FROM USER_INFO U
    WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31') U
LEFT OUTER JOIN ONLINE_SALE O
ON O.USER_ID = U.USER_ID
WHERE O.SALES_DATE IS NOT NULL
GROUP BY YEAR, MONTH
ORDER BY 1,2;