-- 코드를 입력하세요
# SELECT
#     MONTH(START_DATE) AS MONTH,
#     CAR_ID,
#     COUNT(*) AS RECORDS
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE DATE_FORMAT(START_DATE, '%Y-%m') >= '2022-08' 
# AND DATE_FORMAT(END_DATE, '%Y-%m') <= '2022-10'
# GROUP BY 1, 2
# HAVING COUNT(*) >= 5
# ORDER BY 1, 2 DESC

SELECT
    MONTH(START_DATE) AS MONTH,
    CAR_ID
    ,COUNT(CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
GROUP BY 1, 2
HAVING CAR_ID IN (SELECT
    CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
GROUP BY CAR_ID
HAVING COUNT(*) >= 5)
ORDER BY MONTH, CAR_ID DESC

