-- 코드를 입력하세요
WITH RECURSIVE Twenty_four AS(
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM Twenty_four
    WHERE HOUR < 23
)

SELECT
    TF.HOUR,
    COUNT(AO.ANIMAL_ID) AS COUNT
FROM Twenty_four TF
LEFT OUTER JOIN ANIMAL_OUTS AO
    ON TF.HOUR = HOUR(AO.DATETIME)
GROUP BY TF.HOUR;