-- 코드를 입력하세요
SELECT
    UB.WRITER_ID,
    UI.NICKNAME,
    SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD UB
INNER JOIN USED_GOODS_USER UI
ON UB.WRITER_ID = UI.USER_ID
WHERE STATUS = 'DONE'
GROUP BY UB.WRITER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY 3