-- 코드를 입력하세요
SELECT
    F.CATEGORY,
    F.PRICE AS MAX_PRICE,
    F.PRODUCT_NAME
FROM FOOD_PRODUCT F
INNER JOIN (SELECT
    CATEGORY,
    MAX(PRICE)
        OVER(
            PARTITION BY CATEGORY
            ORDER BY PRICE DESC) AS MAX_PRICE,
    PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')) AS SF
ON F.CATEGORY = SF.CATEGORY
AND F.PRICE = SF.MAX_PRICE
AND F.PRODUCT_NAME = SF.PRODUCT_NAME
ORDER BY 2 DESC




# 과자 1950 맛있는허니버터칩
# 국 2900 맛있는김치찌개
# 김치 19000 맛있는배추김치
# 식용유 8950 맛있는마조유