-- 코드를 입력하세요
# SELECT 
    # MEMBER_ID,
    # REVIEW_TEXT,
    # DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
# FROM MEMBER_PROFILE M
# NATURAL JOIN REST_REVIEW R
# NATURAL JOIN (SELECT 
#     MEMBER_ID
#     ,COUNT(*) AS CNT
# FROM REST_REVIEW
# GROUP BY MEMBER_ID) SUB_R

# ORDER BY 3, 2

SELECT 
    MEMBER_NAME,
    REVIEW_TEXT,
    DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE
NATURAL JOIN REST_REVIEW
NATURAL JOIN (
    SELECT
        SR.MEMBER_ID,
        RANK()
            OVER(ORDER BY SR.CNT DESC) AS 'RANK'
    FROM (
        SELECT
        MEMBER_ID,
        COUNT(MEMBER_ID) AS CNT
        FROM REST_REVIEW
        GROUP BY 1
        ) SR
    ) SSR
WHERE SSR.RANK = 1
ORDER BY 3, 2;

# SELECT
#     MEMBER_ID,
#     ROW_NUMBER()
#         OVER(ORDER BY CNT DESC) AS 'RANK'
# FROM (
#     SELECT
#     MEMBER_ID,
#     COUNT(*) AS CNT
#     FROM REST_REVIEW
#     GROUP BY 1
#     ) SR