-- 코드를 입력하세요
# SELECT
#     B.AUTHOR_ID,
#     B.CATEGORY,
#     A.AUTHOR_NAME,
#     SUM(BS.SALES * B.PRICE) AS TOTAL_SALES
# FROM BOOK_SALES BS
# LEFT OUTER JOIN BOOK B
# ON BS.BOOK_ID = B.BOOK_ID
# LEFT OUTER JOIN AUTHOR A
# ON B.AUTHOR_ID = A.AUTHOR_ID
# WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
# GROUP BY B.AUTHOR_ID, B.CATEGORY
# ORDER BY BS.BOOK_ID, B.CATEGORY DESC;

SELECT
    B.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(BS.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK_SALES BS
INNER JOIN BOOK B
ON B.BOOK_ID = BS.BOOK_ID
INNER JOIN AUTHOR A
ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE DATE_FORMAT(BS.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY 
    B.AUTHOR_ID,
    B.CATEGORY
ORDER BY B.AUTHOR_ID, B.CATEGORY DESC;