-- 코드를 입력하세요
SELECT
    A.CAR_ID,
    IF(B.CAR_ID IS NOT NULL, B.AVILABILITY, '대여 가능') AS AVILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
LEFT OUTER JOIN (
    SELECT
        CAR_ID,
        '대여중' AS AVILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE DATE_FORMAT(START_DATE, '%Y-%m-%d') <= '2022-10-16'
    AND DATE_FORMAT(END_DATE, '%Y-%m-%d') >= '2022-10-16'
    GROUP BY CAR_ID) B
ON A.CAR_ID = B.CAR_ID
GROUP BY CAR_ID
ORDER BY 1 DESC;