-- 코드를 입력하세요
SELECT
    DISTINCT O.USER_ID,
    O.PRODUCT_ID
FROM ONLINE_SALE O
INNER JOIN (SELECT
    ONLINE_SALE_ID,
    USER_ID,
    PRODUCT_ID
FROM ONLINE_SALe) SO
ON O.USER_ID = SO.USER_ID
AND O.PRODUCT_ID = SO.PRODUCT_ID
AND O.ONLINE_SALE_ID <> SO.ONLINE_SALE_ID
ORDER BY 1, 2 DESC