-- 코드를 입력하세요
# SELECT
#     CAR_TYPE,
#     COUNT(*) AS CARS
# FROM CAR_RENTAL_COMPANY_CAR
# GROUP BY CAR_TYPE
# HAVING OPTIONS LIKE ''
# ORDER BY 1

SELECT
    CAR_TYPE,
    SUM(OPTIONS LIKE '%열선시트%'
    OR OPTIONS LIKE '%통풍시트%'
    OR OPTIONS LIKE '%가죽시트%') AS CARS
FROM CAR_RENTAL_COMPANY_CAR
GROUP BY CAR_TYPE
ORDER BY 1